@url = https://8080-amethyst-bee-ryt0y2i0.ws-us21.gitpod.io

###
GET {{url}}/filmes

###
POST {{url}}/filmes
Content-Type: application/json

{
    "titulo" : "Exemplo"
}

###
Put {{url}}/filmes/4
Content-Type: application/json

{
    "titulo" : "Ghostbusters"
}

###
DELETE {{url}}/filmes
Content-Type: application/json

{
    "id" : 3
}


